### ISSUE TITLE
Test output order incorrect when using ref requests

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#245]
### common.http
```
{{
  module.exports = require('../../tests/')
}}

### Test common
# @name common
https://httpbin.org/status/200

{{
  tests.status.is(test, response, { val: 200 })
}}
```

### 245.http
```
# @import ./common.http
{{
  module.exports = require('../../tests/')
}}

### Test 1
# @ref common
https://httpbin.org/status/200

{{
  tests.status.is(test, response, { val: 200 })
}}

### Test 2
POST https://httpbin.org/post
Content-Type: application/json

{{_undefinedStuff}}

{{
  tests.status.is(test, response, { val: 200 })
}}
```

### Execution

Running:
```
httpyac --all ./requests/bugs/245.http --output short
```

We get:
```
---------------------

=== Test common ===

GET https://httpbin.org/status/200
=> 200 (741 ms, 184 B)
✓ Status is valid
✓ Status is valid

---------------------

=== Test 1 ===

GET https://httpbin.org/status/200
=> 200 (530 ms, 184 B)
expression _undefinedStuff throws error
ReferenceError: _undefinedStuff is not defined
    at Object.<anonymous> (/httpyac-experiments/requests/bugs/245.http:19:20)
    at yt (/.nvm/versions/node/v17.3.1/lib/node_modules/httpyac/dist/index.js:3:40858)
    at Vt (/.nvm/versions/node/v17.3.1/lib/node_modules/httpyac/dist/index.js:3:41400)
    at /.nvm/versions/node/v17.3.1/lib/node_modules/httpyac/dist/index.js:3:44177
    at ee (/.nvm/versions/node/v17.3.1/lib/node_modules/httpyac/dist/index.js:2:30407)
    at Object.li [as action] (/.nvm/versions/node/v17.3.1/lib/node_modules/httpyac/dist/index.js:3:44142)
    at qt.<anonymous> (/.nvm/versions/node/v17.3.1/lib/node_modules/httpyac/node_modules/hookpoint/dist/index.js:1:2762)
    at Generator.next (<anonymous>)
    at u (/.nvm/versions/node/v17.3.1/lib/node_modules/httpyac/node_modules/hookpoint/dist/index.js:1:1262)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

---------------------

=== Test 2 ===

POST https://httpbin.org/post
=> 200 (999 ms, 627 B)
✓ Status is valid

3 requests tested (3 succeeded, 0 failed)
```

There are 2 issues I can see here:
1. `test common` has the result of its own test, plus the test of the request which is referencing it
2. `Test 1` does not have the result of its own test (see `1` above), but instead does have an error related to `Test 2`

As a side note... I wonder if execution should be abandoned on throw... 🤔

Sorry to always be the bearer of bad news... 😇

**Comment by AnWeber** [comment]
> Sorry to always be the bearer of bad news... 😇

Do you know [300 and how to deal with bearers of bad news ](https://c.tenor.com/xPiy9cJaMFoAAAAd/sparta-kick.gif) in the movie? But seriously. I really appreciate your input. Especially your idea with variables in title. It would be useful in loops.:-)

**Comment by AnWeber** [comment]
> As a side note... I wonder if execution should be abandoned on throw... 🤔

It was once a workaround for AnWeber/vscode-httpyac#95, but is now already prevented differently. Throwing a error makes more sense.

**Comment by AnWeber** [comment]
The order also use of `@ref` already works better. There is still a problem when messages are written before using `@ref`. The solution to this problem is also related to #243. I have to think about that.

**Comment by AnWeber** [comment]
The behavior is fixed with the latest version (v5.4.0). There is one more case, if console outputs are already generated before `# @ref` is executed, they would currently not be output correctly. I have currently neglected this case.

**Comment by gerukin** [comment]
I'm not entirely sure what you mean here. I still have this problem:

Running this (same as before):
```
# @import ./common.http
{{
  module.exports = require('../../tests/')
}}

### Test 1
# @ref common
https://httpbin.org/status/200

{{
  tests.status.is(test, response, { val: 200 })
}}

### Test 2
POST https://httpbin.org/post
Content-Type: application/json

{{_undefinedStuff}}

{{
  tests.status.is(test, response, { val: 200 })
}}
```

I get this
```
---------------------

=== Test common ===

GET https://httpbin.org/status/200
=> 200 (751 ms, 184 B)
✓ Status is valid

---------------------

=== Test 1 ===

GET https://httpbin.org/status/200
=> 200 (555 ms, 184 B)
✓ Status is valid
expression _undefinedStuff throws error
https://httpbin.org/post {
  protocol: 'HTTP',
  url: 'https://httpbin.org/post',
  method: 'POST',
...
```

1. Run `test 1`:
    1. Run @ref (`common`) => `common` header + result (ok)
    2. Run `test 1` => `test 1` header + result (ok)
2. Running test 2 => no header + result (error)

The order now seems fine, but the throw may prevent the proper logging of the test info.

**Comment by AnWeber** [comment]
@gerukin I think your problem here is still the lack of output that Test2 is currently running. Correct?

**Comment by gerukin** [comment]
Yes that's right. Here the throw is happening in `test 2` but the output doesn't mention anything about it. I think it's a tiny issue but it would be a bit clearer if the separator were always logged, even if something throws in the request:
```

---------------------

expression _worstCaseScenario throws error
```

Of course, the ideal would probably be something like:
```

---------------------

=== Test name ===
expression _iDontExist throws error
```
But this might not be possible if the issue is in the title itself for example (assuming expressions in titles).

Anyway, food for thought. I think it's a very minor issue, but it's not always that easy to identify what is throwing (ex: running several files - for which the execution order is not guaranteed I think) using similar code in different contexts.

**Comment by AnWeber** [comment]
@gerukin I agree with you that in case of error it would be better to output the title as well. I just don't have a nice solution yet. I'll create my own ticket to make it more visible again.
